name:                project
version:             0.1.0.0
github:              "kevin-meyers/project"
license:             BSD3
author:              "Kevin Meyers"
maintainer:          "kevinm1776@gmail.com"
copyright:           "mit"

extra-source-files:
- README.md
- ChangeLog.md
- app/Geometry/

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kevin-meyers/project#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - project

tests:
  project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - project
